create table if not exists public.runs (
    id text primary key,
    crew_name text not null,
    trigger_source text not null,
    status text not null,
    lead_mode text,
    lead_query text,
    target_country text,
    proposal_language text,
    currency text,
    max_companies integer,
    test_mode boolean not null default true,
    started_at text not null,
    finished_at text,
    last_heartbeat_at text not null,
    current_task text,
    current_agent text,
    total_tokens integer not null default 0,
    prompt_tokens integer not null default 0,
    completion_tokens integer not null default 0,
    cached_prompt_tokens integer not null default 0,
    successful_requests integer not null default 0,
    estimated_cost_usd double precision not null default 0,
    approval_count integer not null default 0,
    error_message text,
    inputs_json jsonb not null default '{}'::jsonb,
    metadata_json jsonb not null default '{}'::jsonb
);

create index if not exists runs_status_started_at_idx
    on public.runs (status, started_at desc);

create table if not exists public.task_events (
    id bigint generated by default as identity primary key,
    run_id text not null references public.runs (id) on delete cascade,
    task_name text not null,
    task_order integer not null,
    agent_role text,
    model_name text,
    status text not null,
    started_at text,
    finished_at text,
    summary text,
    excerpt text,
    output_path text,
    prompt_tokens integer not null default 0,
    completion_tokens integer not null default 0,
    total_tokens integer not null default 0,
    estimated_cost_usd double precision not null default 0,
    metadata_json jsonb not null default '{}'::jsonb,
    unique (run_id, task_name)
);

create index if not exists task_events_run_id_task_order_idx
    on public.task_events (run_id, task_order asc);

create table if not exists public.assets (
    id text primary key,
    run_id text not null references public.runs (id) on delete cascade,
    company_name text,
    asset_type text not null,
    title text not null,
    path text not null,
    status text not null default 'generated',
    version integer not null default 1,
    created_at text not null,
    metadata_json jsonb not null default '{}'::jsonb
);

create index if not exists assets_run_id_created_at_idx
    on public.assets (run_id, created_at desc);

create table if not exists public.approval_items (
    id text primary key,
    run_id text not null references public.runs (id) on delete cascade,
    company_name text,
    title text not null,
    asset_bundle_json jsonb not null default '[]'::jsonb,
    status text not null,
    priority integer not null default 0,
    created_at text not null,
    decided_at text,
    rejection_reason text,
    reroute_targets_json jsonb not null default '[]'::jsonb,
    metadata_json jsonb not null default '{}'::jsonb
);

create index if not exists approval_items_status_created_at_idx
    on public.approval_items (status, created_at desc);

create index if not exists approval_items_run_id_created_at_idx
    on public.approval_items (run_id, created_at desc);

create table if not exists public.notifications (
    id bigint generated by default as identity primary key,
    run_id text references public.runs (id) on delete cascade,
    kind text not null,
    status text not null,
    subject text not null,
    recipient text not null,
    created_at text not null,
    metadata_json jsonb not null default '{}'::jsonb
);

create index if not exists notifications_created_at_idx
    on public.notifications (created_at desc);

-- Optional: create a private bucket for generated assets and PDFs.
-- insert into storage.buckets (id, name, public)
-- values ('sales-factory-assets', 'sales-factory-assets', false)
-- on conflict (id) do nothing;
